name: "Build and draft a release"

on:
  workflow_dispatch:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write
  discussions: write

jobs:
  build-and-draft-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Build package
        run: |
          pip install build
          python -m build

      - name: Remove `v` in tag name
        uses: mad9000/actions-find-and-replace-string@5
        id: tagNameReplaced
        with:
          source: ${{ github.ref_name }}
          find: "v"
          replace: ""

      - name: Draft a release
        uses: softprops/action-gh-release@v2
        with:
          discussion_category_name: New releases
          draft: true
          generate_release_notes: true
          files: |
            dist/arcaea_offline-${{ steps.tagNameReplaced.outputs.value }}*.whl
            dist/arcaea-offline-${{ steps.tagNameReplaced.outputs.value }}.tar.gz
